export { GetSpotsInput } from '../spot_service_models/get_spots';
export { PostSpotInput } from '../spot_service_models/post_spot';
export { DeleteSpotInput } from '../spot_service_models/delete_spot';
export { GetForecastsInput } from '../forecast_service_models/get_forecasts';
export { GetPossibleForecastsInput } from '../forecast_service_models/get_possible_forecasts';
export { GetRankedForecastsInput } from '../forecast_service_models/get_ranked_forecasts';
export { GetForecastsHourlyInput } from '../forecast_service_models/get_forecasts_hourly';
export { GetPossibleForecastsHourlyInput } from '../forecast_service_models/get_possible_forecasts_hourly';
export { GetRankedForecastsHourlyInput } from '../forecast_service_models/get_ranked_forecasts_hourly';
