export { GetLocationsInput } from '../location_service_models/get_locations';
export { PostLocationInput } from '../location_service_models/post_location';
export { DeleteLocationInput } from '../location_service_models/delete_location';
export { GetForecastsInput } from '../forecast_service_models/get_forecasts';
export { GetPossibleForecastsInput } from '../forecast_service_models/get_possible_forecasts';
export { GetRankedForecastsInput } from '../forecast_service_models/get_ranked_forecasts';
export { GetForecastsHourlyInput } from '../forecast_service_models/get_forecasts_hourly';
export { GetPossibleForecastsHourlyInput } from '../forecast_service_models/get_possible_forecasts_hourly';
export { GetRankedForecastsHourlyInput } from '../forecast_service_models/get_ranked_forecasts_hourly';
